apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: "-15m"
        spanEndTimeShift: "15m"
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9091
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://host.docker.internal:9092
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([0-9a-f]{32})"'
          datasourceUid: tempo
          url: "$${__value.raw}"
